# Generated by Django 4.0.6 on 2022-10-01 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('right_answer', models.TextField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('round_for_question', models.IntegerField(blank=True, default=1, verbose_name='Раунд ответа')),
                ('author', models.CharField(default='Dmitrii', max_length=16, verbose_name='Автор вопроса')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/game_1/questions', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('round_for_question',),
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('header', models.TextField(blank=True, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/game_1/rules/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Код комнаты')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('round', models.IntegerField(blank=True, default=1, verbose_name='Раунд')),
                ('status', models.CharField(blank=True, choices=[('gameover_room', 'Игра закончена'), ('waiting_room', 'Игра создана'), ('result_room', 'Смотрим ответы'), ('waiting_typing_room', 'Ждем ответы'), ('result_list_room', 'Вспомним все ответы'), ('typing_room', 'Печатаем ответы')], default='main_room', max_length=32, verbose_name='Статус игры')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_owner_vue', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('players', models.ManyToManyField(blank=True, related_name='game_players_vue', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ('owner', 'create_time'),
            },
        ),
        migrations.CreateModel(
            name='AnswerPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('round_of_answer', models.IntegerField(verbose_name='Раунд ответа')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_player_vue', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_1_vue.gameroom', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('room',),
            },
        ),
    ]
