# Generated by Django 4.0.6 on 2022-10-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_1_vue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerplayers',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_vue', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(blank=True, choices=[('result_room', 'Смотрим ответы'), ('result_list_room', 'Вспомним все ответы'), ('gameover_room', 'Игра закончена'), ('waiting_typing_room', 'Ждем ответы'), ('typing_room', 'Печатаем ответы'), ('waiting_room', 'Игра создана')], default='main_room', max_length=32, verbose_name='Статус игры'),
        ),
    ]
