# Generated by Django 4.0.6 on 2022-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_1_vue', '0002_alter_answerplayers_player_alter_gameroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(blank=True, choices=[('result_room', 'Смотрим ответы'), ('typing_room', 'Печатаем ответы'), ('gameover_room', 'Игра закончена'), ('waiting_room', 'Игра создана'), ('waiting_typing_room', 'Ждем ответы'), ('result_list_room', 'Вспомним все ответы')], default='main_room', max_length=32, verbose_name='Статус игры'),
        ),
    ]
